version: "3"

services:
    influxdb:
        build: ./influxdb
        container_name: influxdb
        volumes:
            - ${INFLUXDB_DATA}:/var/lib/influxdb
        restart: always
        env_file:
            - .env

    telegraf:
        build: ./telegraf
        container_name: telegraf
        links:
            - influxdb
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
            
    grafana:
        build: ./grafana
        container_name: grafana
        ports: 
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        volumes:
            - /var/lib/grafana
            - /var/log/grafana
            - /var/lib/grafana/plugins
        restart: always
        env_file:
            - .env
