version: "3"


services:

    telegraf:
        build: ./telegraf
        container_name: telegraf
        ports:
            - "${STATSD_PORT}:8125/udp"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${TELEGRAF_DATA}:/tmp/influx/
        privileged: true
        restart: always
        env_file:
            - .env

    influxdb:
        build: ./influxdb
        container_name: influxdb
        volumes:
            - ${INFLUXDB_DATA}:/var/lib/influxdb
        restart: always
        env_file:
            - .env
            
    grafana:
        build: ./grafana
        container_name: grafana
        ports: 
            - "${GRAFANA_PORT}:3000"
        restart: always
        env_file:
            - .env
